### ISSUE TITLE
Embed Google Analytics config map that contains the whole script block

### ISSUE THREAD

**Issue by ywkim312** [IN-CORE/incore-helm#144]
The config map for the documentations needs to contain the whole script block. So create a config map that contains the whole script block

**Comment by longshuicy** [comment]
The incore-ui config map would need to contain the whole script block as well. I just haven't had time to refactor that.

**Comment by ywkim312** [comment]
> The incore-ui config map would need to contain the whole script block as well. I just haven't had time to refactor that.

If you modify this PR, I will create helm PR base on this

**Comment by ywkim312** [comment]
This has already been addressed
